language: go

go:
  - "1.10.x"
  - "1.9.x"
  - master

install:
  - go get -u github.com/golang/dep/...
  - dep ensure
  - go get -v ./...

script:
  - go vet
  - go test -v -cover ./...
  - go build .
