package rhvsdk

import "time"

type Vm struct {
	AffinityLabels              AffinityLabelSlice
	Applications                ApplicationSlice
	Bios                        Bios
	Cdroms                      CdromSlice
	Cluster                     Cluster
	Comment                     string
	Console                     Console
	Cpu                         Cpu
	CpuProfile                  CpuProfile
	CpuShares                   int64
	CreationTime                time.Time
	CustomCompatibilityVersion  Version
	CustomCpuModel              string
	CustomEmulatedMachine       string
	CustomProperties            CustomPropertySlice
	DeleteProtected             bool
	Description                 string
	DiskAttachments             DiskAttachmentSlice
	Display                     Display
	Domain                      Domain
	ExternalHostProvider        ExternalHostProvider
	Floppies                    FloppySlice
	Fqdn                        string
	GraphicsConsoles            GraphicsConsoleSlice
	GuestOperatingSystem        GuestOperatingSystem
	GuestTimeZone               TimeZone
	HasIllegalImages            bool
	HighAvailability            HighAvailability
	Host                        Host
	HostDevices                 HostDeviceSlice
	Id                          string
	Initialization              Initialization
	InstanceType                InstanceType
	Io                          Io
	KatelloErrata               KatelloErratumSlice
	LargeIcon                   Icon
	Lease                       StorageDomainLease
	Memory                      int64
	MemoryPolicy                MemoryPolicy
	Migration                   MigrationOptions
	MigrationDowntime           int64
	MultiQueuesEnabled          bool
	Name                        string
	NextRunConfigurationExists  bool
	Nics                        NicSlice
	NumaNodes                   NumaNodeSlice
	NumaTuneMode                NumaTuneMode
	Origin                      string
	OriginalTemplate            Template
	Os                          OperatingSystem
	Payloads                    PayloadSlice
	Permissions                 PermissionSlice
	PlacementPolicy             VmPlacementPolicy
	Quota                       Quota
	ReportedDevices             ReportedDeviceSlice
	RngDevice                   RngDevice
	RunOnce                     bool
	SerialNumber                SerialNumber
	Sessions                    SessionSlice
	SmallIcon                   Icon
	Snapshots                   SnapshotSlice
	SoundcardEnabled            bool
	Sso                         Sso
	StartPaused                 bool
	StartTime                   time.Time
	Stateless                   bool
	Statistics                  StatisticSlice
	Status                      VmStatus
	StatusDetail                string
	StopReason                  string
	StopTime                    time.Time
	StorageDomain               StorageDomain
	StorageErrorResumeBehaviour VmStorageErrorResumeBehaviour
	Tags                        TagSlice
	Template                    Template
	TimeZone                    TimeZone
	TunnelMigration             bool
	Type_                       VmType
	Usb                         Usb
	UseLatestTemplateVersion    bool
	VirtioScsi                  VirtioScsi
	VmPool                      VmPool
	Watchdogs                   WatchdogSlice
}
